config/routes.rb
Pixtr::Application.routes.draw do
  ## this route maps a url to a controller and an action
  ## controller#action
  ## actions are methods
  ## index is a method
  ## if you have a route that goes to a method, that method is an action
  ## all actions are methods, but not all methods are actions.  
  
  get "/galleries/random" => "random_galleries#show"


  root "galleries#index"
  resources :galleries do
    resources :images, shallow: true
  end
## or
## get "galleries/new" => "galleries#new"
## get "/galleries/:id" => "galleries#show", 
## as: :gallery
## post "/galleries" => "galleries#create" ## so that it persists to the database
## get "/galleries/:id/edit" => "galleries#edit"
## patch "/galleries/:id" => "galleries#update" ##this one persists to the database
## delete "/galleries/:id" => "galleries#destroy"
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :images
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index ## no need to erb :index, Rails does this automatically.    
    @galleries = Gallery.all
  end       ## index is a method or action
  def show
    @gallery = Gallery.find(params[:id])
  end
  def new ##presentation of the form
    @gallery = Gallery.new  
  end
  def create ##persistence to the database
    gallery = Gallery.create(gallery_params) ##gallery_params instead of params[:gallery]
    redirect_to gallery_path(gallery)##"/galleries/#{gallery.id}"
  end
  def edit ##presentation of form
    @gallery = Gallery.find(params[:id])
  end
  def update ##persistence to the database
    gallery = Gallery.find(params[:id])
    gallery.update(gallery_params)
    redirect_to gallery_path(gallery)##"/galleries/#{gallery.id}"
  end
  def destroy
    gallery = Gallery.find(params[:id])
    gallery.destroy
    redirect_to root_path
  end

private  

  def gallery_params  ##strong parameter stuff
    params.require(:gallery).permit(:name)
  end
end         ## this renders an index view

app/controllers/images_controller.rb
class ImagesController < ApplicationController


  def new
    @gallery = Gallery.find(params[:gallery_id])
    @image = Image.new
  end
  def create
    gallery = Gallery.find(params[:gallery_id]) ##find the gallery
    gallery.images.create(image_params) ## create the image throught the gallery
    redirect_to gallery ## redirect to the gallery
  end
  def show
    @image = Image.find(params[:id])
  end
  def edit
    @image = Image.find(params[:id])
  end
def update ##persistence to the database
    image = Image.find(params[:id])
    image.update(image_params)
    redirect_to image##"/galleries/#{gallery.id}"
end
def destroy
  image = Image.find(params[:id])
  image.destroy
  redirect_to image.gallery ## in lieu of gallery_path(image.gallery_id)
end

private  

  def image_params  ##strong parameter stuff
    params.require(:image).permit(
      :name, 
      :description, 
      :url
    )
  end
end         ## this renders an index view

app/controllers/random_galleries_controller.rb
class RandomGalleriesController < ApplicationController
  def show
    gallery = Gallery.all.sample
    redirect_to "/galleries/#{gallery.id}"
    ## or
    ## render 'galleries/show'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/galleries/edit.html.erb
<%= form_for(@gallery) do |form| %>
  <%= form.text_field :name %>
  <%= form.submit "Update Gallery" %>
<% end %>

app/views/galleries/index.html.erb
<h2>My Galleries</h2>
<nav><%= link_to "Add New Gallery" , new_gallery_path %> </nav>

<div>
<ul>
<% @galleries.each do |gallery| %>
<li><h3>  <%= link_to gallery.name, gallery_path(gallery) %> </h3></li>
<% end %>
</ul>
</div>

app/views/galleries/new.html.erb
<header>Add New Gallery</header>
<div>
<%= form_for(@gallery) do |form| %>
  <%= form.text_field :name %>
  <%= form.submit "Create Gallery" %>
<% end %>
</div>

app/views/galleries/show.html.erb
<h1> <%= @gallery.name %> </h1>

<%= link_to "Edit" , edit_gallery_path(@gallery) %> 
<%= link_to "Delete" , @gallery, method: :delete %> <!--polymorphic path instead of gallery_path(@gallery) 
                                                        takes a class name, lowercases it, and 
                                                        creates a url contextually-->
<%= link_to "Add new image" , new_gallery_image_path(@gallery) %> <!--syntax for nested path
<!--{method: :delete} where method is a key and :delete is a symbor for the delete method -->

<% @gallery.images.each do |image| %>

  <p> <%= image.name %> : </p>
  <p> stuff <%= image.description %></p>
  
  <%= link_to image do %> 
    <img src="<%= image.url %>" >
    <% end %>
<% end %> 

app/views/images/edit.html.erb
<h2> Edit Picture </h2>

<%= form_for(@image) do |form| %>
  <%= form.text_field :name %>
  <%= form.text_field :description %>
  <%= form.text_field :url %>
  <%= form.submit "Update Image" %>
<% end %>

app/views/images/new.html.erb
<%= form_for([@gallery, @image]) do |form| %>
  <%= form.text_field :name , placeholder: "Name"%>
  <%= form.text_field :description , placeholder: "Description" %>
  <%= form.text_field :url , placeholder: "URL"%>
  <%= form.submit "Create new image" %>
<% end %>

app/views/images/show.html.erb
<h2><%= @image.name %></h2>
<p> <%= @image.description %> </p>
<nav>
  <%= link_to "Edit Picture" , edit_image_path(@image) %>
  <%= link_to "Delete Picture" , @image, method: :delete, confirm: "Are you sure you want to delete this image?" %>
</nav>
<img src="<%= @image.url %>">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pixtr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= link_to 'Sign out', sign_out_path, :method => :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>



<%= yield %>

</body>
</html>